### ISSUE TITLE
Need a logo

### ISSUE THREAD

**Issue by misken** [misken/hillmaker#64]
Be nice to have a logo to put on the docs page and the GitHub repo

**Comment by jwnorm** [comment]
Here is my first pass at a logo:

![hillmaker_logo](https://github.com/misken/hillmaker/assets/35746634/c2499fb4-3659-46ed-bab5-90e6163d63e3)

The sketch I originally sent you looked goofy when I started to create it in PhotoShop. I think this is a lot cleaner looking, but still hints at the namesake of `hillmaker`.

Let me know if you have any notes on the colors, shapes, or font. All that stuff is pretty easy to edit. I can also make a version that has harsh corners instead of the rounded ones if you prefer.

**Comment by jwnorm** [comment]
I adjusted the hill shapes to be less symmetrical and made the text all lowercase. I was thinking the same thing since `hillmaker` is always written that way.

![hillmaker_logo-draft](https://github.com/misken/hillmaker/assets/35746634/0c802e64-8256-4d45-8a9e-bc19d2fc0f05)

I think this looks much better (might be because more of the green fills up the image?). The plot looks more like something that could actually be generated using the application and not just two hills. Good blending of the sketch I sent you and the V1 of the logo.

**Comment by misken** [comment]
I like it! What font is that?

**Comment by jwnorm** [comment]
Something called `DPSDbeyond`. I am using [Photopea](https://www.photopea.com/) for fine tuning, so not sure if it is exclusive to that in some way.

> I like it! What font is that?

**Comment by jwnorm** [comment]
In case you were wondering, here is what it looks like if there are no gaps between the bars.

![hillmaker_logo-filled](https://github.com/misken/hillmaker/assets/35746634/9c0913f2-0377-4ed1-b98c-6d83c5c1e145)

I don't like it as much. The darker green is too harsh without the extra lighter tones to balance it out.

**Comment by misken** [comment]
Hmm. I do like them both. Let's let it sit for a bit and see how we feel in a day or two. 

If it's not too much trouble, can you try a few other fonts for comparison?

**Comment by jwnorm** [comment]
> Hmm. I do like them both. Let's let it sit for a bit and see how we feel in a day or two.
> 
> If it's not too much trouble, can you try a few other fonts for comparison?

I sampled a bunch of monospaced fonts (probably too many):

## Cousine
![cousine](https://github.com/misken/hillmaker/assets/35746634/40d4f84a-41f3-41e6-834e-72c7226c8dd1)

## Share Tech Mono
![share_tech_mono](https://github.com/misken/hillmaker/assets/35746634/fcbe983f-4eb4-443c-8935-c52d80d5361e)

## Inconsolata
![inconsolata](https://github.com/misken/hillmaker/assets/35746634/a2e76c91-3c77-4ee5-b5c2-467eecd0e06b)

## Hack
![hack](https://github.com/misken/hillmaker/assets/35746634/28c03f98-b343-4ad7-bf48-1090b017ff5d)

## Redhat Mono
![redhat_mono](https://github.com/misken/hillmaker/assets/35746634/7e4af457-4b33-464f-85d6-665078eb7924)

## JetBrains Mono
![jetbrains_mono](https://github.com/misken/hillmaker/assets/35746634/8ca7c77e-405e-47ae-9ccf-2e46573e32d4)

## Fira Mono
![fira_mono](https://github.com/misken/hillmaker/assets/35746634/1e8b4f25-16b5-47b0-b432-cf2e4d35a33d)

## BP Mono
![bp_mono](https://github.com/misken/hillmaker/assets/35746634/fec89914-c3a3-4c44-b738-19ed61a29077)

## Space Mono
![space_mono](https://github.com/misken/hillmaker/assets/35746634/bf07dfe5-1d1d-4ae0-994c-b0bb4efcee29)

## Martian Mono
![martian_mono](https://github.com/misken/hillmaker/assets/35746634/2f0d2052-1dc9-43e0-b95f-db1599b3d9fd)

## DM Mono
![dm_mono](https://github.com/misken/hillmaker/assets/35746634/fb3d2ebc-bcc1-46d8-b260-2812b5d6626e)

## Azaret Mono
![azeret_mono](https://github.com/misken/hillmaker/assets/35746634/9f36e3be-625b-411d-aece-ac81609abd02)

**Comment by misken** [comment]
I think I like the original lower case font and the no gaps between the bars. I've used that version for the docs that are live now. Let me know what you think.

**Comment by jwnorm** [comment]
I agree. Plus, the no gaps version mirrors the default plotting format in the package. It looks good on the docs, but do you need other sizes for the image? I was planning on creating an images folder and throwing in the following:

- png
- svg
- psd (PhotoShop file for future editing if needed)

Would then open a new PR.

**Comment by misken** [comment]
Yes, that would be great. The current size might be a bit big for the docs page? Experiment a bit and I can try them out and we can see they how they look.

**Comment by jwnorm** [comment]
Here is a smaller png (250 x 250):

![hillmaker_logo-small](https://github.com/misken/hillmaker/assets/35746634/3ba41fe3-b75c-4c2e-b2cb-b8db768d5f8b)


Also, I think svg files allow you to easily scale the image. Try this as well to see if you can tune the image size in the docs to whatever looks best:

![hillmaker_logo-filled2](https://github.com/misken/hillmaker/assets/35746634/edc218da-32ba-4617-9658-043f081d1b20)

**Comment by misken** [comment]
Thanks! I'll mess around with these later this evening.

**Comment by misken** [comment]
Logo selected and used on docs page.
