### ISSUE TITLE
Add CI for updating docs

### ISSUE THREAD

**Issue by HLasse** [misken/hillmaker#73]
It seems like managing the documentation (building and pushing) is currently a manual process. Having an action set up on CI for this would probably make maintenance easier in the long run (and would have the added benefit of being able to add a nice green badge with a link to the documentation in the readme). 

Whether you want to add this is up to you, this is just a suggestion. 

openjournals/joss-reviews#6154

**Comment by misken** [comment]
I think I do have this automated but let me describe what I do and you can tell me if there's a better way.

The docs are written in Jupyter notebooks generated with jupyter-book. Due to an [issue](https://github.com/executablebooks/jupyter-book/issues/1348) with how jupyter-book handles conda virtual envs, I run a shell script, `build_docs.sh`,  that changes a key notebook setting in all the notebooks, rebuilds the docs and modifies `docs/_config.yml` so that RTD doesn't try to execute the notebooks when changes are pushed. Then once I push, RTD takes over and builds and publishes the documentation.

**Comment by HLasse** [comment]
Ah, alright - so RTD watches for changes in the docs and automatically updates? That sounds good!

**Comment by misken** [comment]
Yep, exactly. Most of the headaches around documentation are just getting JupyterBook and RTD to play nice together.
